[package]
name = "day24"
version = "0.1.0"
authors = ["Bernardo Chaves <bernardo.amc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
